[install]
state = enabled
is_configured = true
build = 2

[ui]
is_visible = true
label = Splunk Engineering Lab

[launcher]
author = LordMonstey
description = Splunk platform administration and detection-as-code lab for Windows telemetry.
version = 0.4.1

[package]
id = splunk-detection-lab
