[install]
state = enabled
is_configured = true
build = 14

[ui]
is_visible = true
label = Splunk ES Administration

[launcher]
author = A.S
description = Splunk ES administration, MCO, data onboarding, CIM assurance, change governance, and operational reporting.
version = 0.7.3

[package]
id = splunk-detection-lab
