[sysmon_process_create]
search = sourcetype="XmlWinEventLog:Microsoft-Windows-Sysmon/Operational" EventID=1

[sysmon_network_connection]
search = sourcetype="XmlWinEventLog:Microsoft-Windows-Sysmon/Operational" EventID=3

[sysmon_image_load]
search = sourcetype="XmlWinEventLog:Microsoft-Windows-Sysmon/Operational" EventID=7

[sysmon_process_terminate]
search = sourcetype="XmlWinEventLog:Microsoft-Windows-Sysmon/Operational" EventID=5

[sysmon_file_create]
search = sourcetype="XmlWinEventLog:Microsoft-Windows-Sysmon/Operational" EventID=11

[sysmon_registry]
search = sourcetype="XmlWinEventLog:Microsoft-Windows-Sysmon/Operational" (EventID=12 OR EventID=13 OR EventID=14)

[sysmon_dns_query]
search = sourcetype="XmlWinEventLog:Microsoft-Windows-Sysmon/Operational" EventID=22

[sysmon_process_access]
search = sourcetype="XmlWinEventLog:Microsoft-Windows-Sysmon/Operational" EventID=10

[sysmon_file_delete]
search = sourcetype="XmlWinEventLog:Microsoft-Windows-Sysmon/Operational" (EventID=23 OR EventID=26)

[wineventlog_logon_success]
search = sourcetype="XmlWinEventLog:Security" EventID=4624

[wineventlog_logon_failed]
search = sourcetype="XmlWinEventLog:Security" EventID=4625

[wineventlog_account_created]
search = sourcetype="XmlWinEventLog:Security" EventID=4720

[wineventlog_service_install]
search = sourcetype="XmlWinEventLog:System" EventID=7045

[wineventlog_powershell_script]
search = sourcetype="XmlWinEventLog:Microsoft-Windows-PowerShell/Operational" EventID=4104

[linux_authentication]
search = index=os_linux ((sourcetype=linux:auditd audit_type=USER_AUTH) OR (sourcetype=linux:rsyslog app=sshd))

[linux_account_change]
search = index=os_linux ((sourcetype=linux:auditd audit_type="USER_MGMT") OR (sourcetype=linux:rsyslog app="useradd"))

[linux_audit_change]
search = index=os_linux sourcetype=linux:auditd audit_type="CONFIG_CHANGE"

[linux_privileged_endpoint_change]
search = index=os_linux sourcetype=linux:rsyslog app="sudo" (command="/usr/bin/systemctl *" OR command="/usr/sbin/useradd *" OR command="/usr/sbin/usermod *" OR command="/usr/bin/chmod *" OR command="/usr/bin/chown *" OR command="/usr/sbin/auditctl *")

[linux_process_start]
search = index=os_linux sourcetype=linux:auditd audit_type=SYSCALL syscall=59

[linux_service_state]
search = index=os_linux ((sourcetype=linux:journald service=*.service) OR (sourcetype=linux:rsyslog app=systemd service=*.service))
