[eventtype=sysmon_process_create]
process = enabled
endpoint = enabled
report = enabled

[eventtype=sysmon_network_connection]
network = enabled
communicate = enabled
endpoint = enabled

[eventtype=sysmon_image_load]
load = enabled
process = enabled
endpoint = enabled

[eventtype=sysmon_process_terminate]
process = enabled
endpoint = enabled

[eventtype=sysmon_file_create]
filesystem = enabled
endpoint = enabled
write = enabled

[eventtype=sysmon_registry]
registry = enabled
endpoint = enabled

[eventtype=sysmon_dns_query]
network = enabled
resolution = enabled
dns = enabled

[eventtype=sysmon_process_access]
process = enabled
endpoint = enabled

[eventtype=sysmon_file_delete]
filesystem = enabled
endpoint = enabled
delete = enabled

[eventtype=wineventlog_logon_success]
authentication = enabled
success = enabled

[eventtype=wineventlog_logon_failed]
authentication = enabled
failure = enabled

[eventtype=wineventlog_account_created]
change = enabled
account = enabled
identity = enabled

[eventtype=wineventlog_service_install]
change = enabled
endpoint = enabled

[eventtype=wineventlog_powershell_script]
process = enabled
endpoint = enabled

[eventtype=linux_authentication]
authentication = enabled

[eventtype=linux_account_change]
change = enabled
account = enabled

[eventtype=linux_audit_change]
change = enabled
audit = enabled

[eventtype=linux_privileged_endpoint_change]
change = enabled
endpoint = enabled

[eventtype=linux_process_start]
process = enabled
report = enabled

[eventtype=linux_service_state]
service = enabled
report = enabled
