[install]
is_configured = 1

[launcher]
author = A.S
description = Candidat volontairement degrade pour qualification canari du parsing
version = 1.1.0-rc1

[ui]
is_visible = 0
label = Splunk Parsing Canary Qualification
