[idx_recette_parsing]
homePath = $SPLUNK_DB/idx_recette_parsing/db
coldPath = $SPLUNK_DB/idx_recette_parsing/colddb
thawedPath = $SPLUNK_DB/idx_recette_parsing/thaweddb
maxTotalDataSizeMB = 250
frozenTimePeriodInSecs = 604800
repFactor = 0
