[canary:auth]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TRUNCATE = 4096
CHARSET = UTF-8
KV_MODE = none
DATETIME_CONFIG = CURRENT
TIME_PREFIX = \boccurred_at=
TIME_FORMAT = %Y-%m-%dT%H:%M:%SZ
MAX_TIMESTAMP_LOOKAHEAD = 20
TZ = UTC
REPORT-canary-control = canary_control_fields
REPORT-canary-auth = canary_auth_fields
