[XmlWinEventLog:Microsoft-Windows-Sysmon/Operational]
TRANSFORMS-set_sourcetype_sysmon = sysmon_set_sourcetype
EVAL-vendor_product = "Microsoft Sysmon"
EVAL-action = case(EventCode==1,"started", EventCode==5,"stopped", EventCode==3,"connected", EventCode==11,"created", EventCode==12 OR EventCode==13 OR EventCode==14,"modified")
SEDCMD-strip_xmlns = s/xmlns(:[a-z]+)?="[^"]+"//g

[XmlWinEventLog:Security]
EVAL-vendor_product = "Microsoft Windows"

[XmlWinEventLog:Microsoft-Windows-PowerShell/Operational]
EVAL-vendor_product = "Microsoft PowerShell"
