[asset_lookup]
filename = asset.csv
case_sensitive_match = false

[identity_lookup]
filename = identity.csv
case_sensitive_match = false

[allowlist_rundll32]
filename = allowlist_rundll32.csv
case_sensitive_match = false

[suspicious_processes]
filename = suspicious_processes.csv
case_sensitive_match = false
