[tcpout]
defaultGroup = primary_indexers
useACK = true

[tcpout:primary_indexers]
server = SPLUNK_RECEIVER_IP:9997
sslCertPath = $SPLUNK_HOME\etc\auth\server.pem
sslPassword = $1$REPLACE_WITH_YOUR_HASHED_PWD
sslVerifyServerCert = false
