[upgrade_qualification_heartbeat]
disabled = 0
enableSched = 1
cron_schedule = * * * * *
dispatch.earliest_time = -2m@m
dispatch.latest_time = now
schedule_window = 30
search = | makeresults | eval qualification="passed", object="scheduled_search" | table qualification object
